language: node_js

node_js:
- "8"

sudo: required

install:
- npm install
- npm test

script:
- npm run build

before_deploy:
- git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/Open-EO/openeo-api.git gh-pages
- cd gh-pages
- |
  if [[ $TRAVIS_BRANCH == 'master' ]] ; then
    cp ../redoc.html index.html
    cp ../errors.json errors.json
    cp -r ../assets assets
  fi
- |
  if [[ $TRAVIS_BRANCH == 'draft' ]] ; then
    rm -rf draft
    mkdir -p draft
    cp ../redoc.html draft/index.html
    cp ../errors.json draft/errors.json
    cp -r ../assets draft/assets
  fi
- |
  if [ -n "$TRAVIS_TAG" ] ; then
    rm -rf $TRAVIS_TAG
    mkdir -p $TRAVIS_TAG
    cp ../redoc.html $TRAVIS_TAG/index.html
    cp ../errors.json $TRAVIS_TAG/errors.json
    cp -r ../assets $TRAVIS_TAG/assets
  fi

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: gh-pages
    keep-history: true
    name: openEO CI
    email: openeo.ci@uni-muenster.de
    on:
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: gh-pages
    keep-history: true
    name: openEO CI
    email: openeo.ci@uni-muenster.de
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|draft)$