site_name: openEO API 0.4.0
nav:
  - Prologue:
    - Introduction: index.md
    - Glossary: glossary.md
    - Contributor Code of Conduct: codeofconduct.md
    - Changelog: changelog.md
  - Getting started:
    - Users: gettingstarted-users.md
    - Back-end Providers: gettingstarted-backends.md
    - Client Developers: gettingstarted-clients.md
    - Examples (proof of concept): examples-poc.md
  - Architecture: arch.md
  - Features:
    - User Management and Accounting: usermanagement.md
    - Jobs: jobs.md
    - UDFs: udfs.md
  - Development guidelines:
    - Software Development: guidelines-software.md
    - Client Library Development: guidelines-clients.md
    - API Specification: guidelines-api.md
  - API:
    - Data Discovery: collections.md
    - Processes: processes.md
    - Process Graphs: processgraphs.md
    - Error Handling: errors.md
    - CORS: cors.md
  - Core API Reference: apireference.md
  - Subscriptions API Reference: apireference-subscriptions.md
  - Process Reference: processreference.md
theme:
  name: 'material'
repo_url: https://github.com/Open-EO/openeo-api
use_directory_urls: true
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
plugins:
  - search
  - macros